name: Contract tests

on:
  workflow_dispatch:
    inputs:
      frontend-image:
        description: 'Frontend image registry path'
        default: 'evercoinx/faraway:nft-collection-deployer-frontend'
        required: true
        type: string
      backend-image:
        description: 'Backtend image registry path'
        default: 'evercoinx/faraway:nft-collection-deployer-backend'
        required: true
        type: string

jobs:
  tests:
    needs: [frontend, backend]
    runs-on: ubuntu-latest
    env:
      QUICKNODE_TOKEN: ${{ secrets.QUICKNODE_TOKEN }}
      WALLET_PRIVATE_KEY: ${{ secrets.WALLET_PRIVATE_KEY }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
        - name: Run frontend container
        run: docker run -p 3000:3000 -d ${{ inputs.frontend-image }}
      - name: Run backend container
        run: docker run -p 4000:4000 -d ${{ inputs.backend-image }}
      - name: Install dependencies
        run: npm ci
      - name: integration tests
        run: npm run test:integration

      # - name: Install Playwright Browsers
      #   run: npx playwright install --with-deps
      # - name: run UI tests
      #   run: npm run test:ui
      # - uses: actions/upload-artifact@v3
      #   if: always()
      #   with:
      #     name: playwright-report
      #     path: playwright-report/
      #     retention-days: 3
